language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
matrix:
  allow_failures:
    - python: "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: nosetests --verbose --with-coverage --cover-package=edx_dl

after_success:
  coveralls
